name: Build RetroArch Core
on:
  push:
    branches:
      - master

jobs:   
  v4-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libvorbis-dev libsdl2-dev libxxf86vm-dev libx11-xcb-dev
      - name: Build RetroArch Core
        run: |
          make clean
          make
      - name: Upload
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: libretro-genesisplusgx-linux
          path: genesis_plus_gx_libretro.so
